<?php
require_once __DIR__.'/includes/bootstrap.php';requireLogin();$pdo=db();$y=(int)date('Y');$m=(int)date('n');[$start,$end]=monthBounds($y,$m);
$s=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='expense' THEN amount ELSE 0 END),0) expense FROM transactions WHERE user_id=? AND transaction_date>=? AND transaction_date<?");$s->execute([currentUserId(),$start,$end]);$t=$s->fetch();$income=(float)$t['income'];$expense=(float)$t['expense'];$net=$income-$expense;
$s=$pdo->prepare("SELECT c.name,SUM(t.amount) total FROM transactions t JOIN categories c ON c.id=t.category_id WHERE t.user_id=? AND t.type='expense' AND t.transaction_date>=? AND t.transaction_date<? GROUP BY c.id,c.name ORDER BY total DESC");$s->execute([currentUserId(),$start,$end]);$cats=$s->fetchAll();$top=array_slice($cats,0,3);
$s=$pdo->prepare('SELECT amount FROM budgets WHERE user_id=? AND year=? AND month=?');$s->execute([currentUserId(),$y,$m]);$budget=(float)($s->fetchColumn()?:0);$bp=$budget>0?min(100,$expense/$budget*100):0;
$s=$pdo->prepare('SELECT * FROM goals WHERE user_id=? ORDER BY id DESC LIMIT 1');$s->execute([currentUserId()]);$goal=$s->fetch();$gp=$goal?min(100,(float)$goal['current_amount']/(float)$goal['target_amount']*100):0;
$pageTitle='Dashboard';include __DIR__.'/includes/header.php';
?>
<div class="page-heading"><div><h1>Dashboard</h1><p><?= e(date('F Y')) ?> overview</p></div><a class="btn primary" href="<?= e(url('add_transaction.php')) ?>">+ Add Transaction</a></div>
<div class="stats-grid"><div class="stat-card"><span>Monthly Income</span><strong><?= money($income) ?></strong></div><div class="stat-card"><span>Monthly Expense</span><strong><?= money($expense) ?></strong></div><div class="stat-card"><span>Net Balance</span><strong><?= money($net) ?></strong></div></div>
<div class="dashboard-grid"><section class="card chart-card"><div class="card-title"><h2>Expense Categories</h2></div><div class="chart-box"><canvas id="expenseChart"></canvas></div><script id="expense-data" type="application/json"><?= json_encode(['labels'=>array_column($cats,'name'),'values'=>array_map('floatval',array_column($cats,'total'))],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></section>
<section class="card"><div class="card-title"><h2>Top 3 Spending Categories</h2></div><?php if(!$top): ?><p class="muted">No expenses this month.</p><?php endif; ?><?php foreach($top as $i=>$r): ?><div class="rank-row"><span><?= $i+1 ?>. <?= e($r['name']) ?></span><strong><?= money($r['total']) ?></strong></div><?php endforeach; ?></section></div>
<div class="dashboard-grid"><section class="card"><div class="card-title"><h2>Monthly Budget</h2><a href="<?= e(url('budget.php')) ?>">Manage</a></div><?php if($budget>0): ?><p><?= money($expense) ?> spent of <?= money($budget) ?></p><div class="progress"><span style="width:<?= e($bp) ?>%"></span></div><strong><?= number_format($expense/$budget*100,1) ?>%</strong><?php else: ?><p class="muted">No budget set for this month.</p><a class="btn secondary" href="<?= e(url('budget.php')) ?>">Set Budget</a><?php endif; ?></section>
<section class="card"><div class="card-title"><h2>Savings Goal</h2><a href="<?= e(url('goals.php')) ?>">Manage</a></div><?php if($goal): ?><p><strong><?= e($goal['name']) ?></strong></p><p><?= money($goal['current_amount']) ?> of <?= money($goal['target_amount']) ?></p><div class="progress"><span style="width:<?= e($gp) ?>%"></span></div><strong><?= number_format($gp,1) ?>%</strong><?php else: ?><p class="muted">No savings goal yet.</p><a class="btn secondary" href="<?= e(url('goals.php')) ?>">Create Goal</a><?php endif; ?></section></div>
<?php include __DIR__.'/includes/footer.php'; ?>
