<?php
require_once __DIR__.'/includes/bootstrap.php';requireLogin();$pdo=db();$errors=[];$editId=(int)($_GET['edit']??0);$editing=null;
if($editId){$s=$pdo->prepare('SELECT * FROM goals WHERE id=? AND user_id=?');$s->execute([$editId,currentUserId()]);$editing=$s->fetch();if(!$editing)$editId=0;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';if($action==='delete'){$id=(int)$_POST['id'];$pdo->prepare('DELETE FROM goals WHERE id=? AND user_id=?')->execute([$id,currentUserId()]);flash('success','Goal deleted.');redirect('goals.php');}
$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$target=(float)($_POST['target_amount']??0);$current=(float)($_POST['current_amount']??0);$date=trim((string)($_POST['target_date']??''));$date=$date!==''?$date:null;if($name==='')$errors[]='Goal name is required.';if($target<=0)$errors[]='Target amount must be greater than zero.';if($current<0)$errors[]='Current amount cannot be negative.';if($date&&!validDate($date))$errors[]='Invalid target date.';
if(!$errors){if($id){$s=$pdo->prepare('UPDATE goals SET name=?,target_amount=?,current_amount=?,target_date=? WHERE id=? AND user_id=?');$s->execute([$name,$target,$current,$date,$id,currentUserId()]);flash('success','Goal updated.');}else{$s=$pdo->prepare('INSERT INTO goals(user_id,name,target_amount,current_amount,target_date) VALUES(?,?,?,?,?)');$s->execute([currentUserId(),$name,$target,$current,$date]);flash('success','Goal created.');}redirect('goals.php');}}
$s=$pdo->prepare('SELECT * FROM goals WHERE user_id=? ORDER BY id DESC');$s->execute([currentUserId()]);$goals=$s->fetchAll();
$pageTitle='Goals';include __DIR__.'/includes/header.php';
?>
<div class="page-heading"><div><h1>Savings Goals</h1><p>Create, update and track your goals.</p></div></div><div class="dashboard-grid"><section class="card"><h2><?= $editing?'Edit Goal':'Create Goal' ?></h2><?php foreach($errors as $e1): ?><div class="alert error"><?= e($e1) ?></div><?php endforeach; ?><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($editing['id']??0) ?>"><label>Name<input name="name" value="<?= e($editing['name']??'') ?>" required></label><label>Target Amount (₹)<input type="number" step="0.01" min="0.01" name="target_amount" value="<?= e($editing['target_amount']??'') ?>" required></label><label>Current Amount (₹)<input type="number" step="0.01" min="0" name="current_amount" value="<?= e($editing['current_amount']??0) ?>" required></label><label>Target Date<input type="date" name="target_date" value="<?= e($editing['target_date']??'') ?>"></label><button type="submit" class="btn primary full"><?= $editing?'Update Goal':'Create Goal' ?></button><?php if($editing): ?><a class="btn secondary full" href="<?= e(url('goals.php')) ?>">Cancel</a><?php endif; ?></form></section><section><?php foreach($goals as $g):$p=min(100,(float)$g['current_amount']/(float)$g['target_amount']*100); ?><div class="card"><div class="card-title"><h2><?= e($g['name']) ?></h2><div><a class="btn tiny" href="<?= e(url('goals.php?edit='.$g['id'])) ?>">Edit</a><form method="post" class="inline" onsubmit="return confirm('Delete this goal?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($g['id']) ?>"><button class="btn tiny danger">Delete</button></form></div></div><p><?= money($g['current_amount']) ?> / <?= money($g['target_amount']) ?></p><div class="progress"><span style="width:<?= e($p) ?>%"></span></div><p><strong><?= number_format($p,1) ?>%</strong><?php if($g['target_date']): ?> · target <?= e(date('d M Y',strtotime($g['target_date']))) ?><?php endif; ?></p></div><?php endforeach; ?><?php if(!$goals): ?><div class="card"><p class="muted">No goals created yet.</p></div><?php endif; ?></section></div>
<?php include __DIR__.'/includes/footer.php'; ?>
