<?php
require_once __DIR__.'/includes/bootstrap.php';requireLogin();$pdo=db();$y=(int)($_GET['year']??date('Y'));$m=(int)($_GET['month']??date('n'));if($m<1||$m>12)$m=date('n');if($y<2000||$y>2100)$y=date('Y');[$start,$end]=monthBounds($y,$m);
$search=trim((string)($_GET['search']??''));$cat=(int)($_GET['category']??0);$payment=$_GET['payment']??'';$type=$_GET['type']??'';$where=['t.user_id=?','t.transaction_date>=?','t.transaction_date<?'];$params=[currentUserId(),$start,$end];
if($search!==''){$where[]='t.description LIKE ?';$params[]='%'.$search.'%';}if($cat>0){$where[]='t.category_id=?';$params[]=$cat;}if(in_array($payment,['cash','debit_card','credit_card'],true)){$where[]='t.payment_method=?';$params[]=$payment;}if(in_array($type,['income','expense'],true)){$where[]='t.type=?';$params[]=$type;}
$s=$pdo->prepare("SELECT t.*,c.name category_name FROM transactions t JOIN categories c ON c.id=t.category_id WHERE ".implode(' AND ',$where)." ORDER BY t.transaction_date DESC,t.id DESC");$s->execute($params);$rows=$s->fetchAll();$categories=$pdo->query('SELECT id,name,type FROM categories WHERE is_active=1 ORDER BY type,name')->fetchAll();
$query=http_build_query($_GET);$pageTitle='Transactions';include __DIR__.'/includes/header.php';
?>
<div class="page-heading"><div><h1>Transactions</h1><p><?= e(date('F Y',strtotime($start))) ?></p></div><div class="actions"><a class="btn primary" href="<?= e(url('add_transaction.php')) ?>">+ Add</a><a class="btn secondary" href="<?= e(url('export/transactions_csv.php'.($query?'?'.$query:''))) ?>">CSV</a><a class="btn secondary" href="<?= e(url('export/transactions_xlsx.php'.($query?'?'.$query:''))) ?>">XLSX</a></div></div>
<section class="card"><form method="get" class="filter-grid"><label>Month<select name="month"><?php for($i=1;$i<=12;$i++): ?><option value="<?= $i ?>" <?= $i===$m?'selected':'' ?>><?= e(date('F',mktime(0,0,0,$i,1))) ?></option><?php endfor; ?></select></label><label>Year<input type="number" name="year" value="<?= e($y) ?>" min="2000" max="2100"></label><label>Search<input name="search" value="<?= e($search) ?>" placeholder="Description"></label><label>Category<select name="category"><option value="0">All</option><?php foreach($categories as $c): ?><option value="<?= e($c['id']) ?>" <?= $cat===(int)$c['id']?'selected':'' ?>><?= e(ucfirst($c['type']).' · '.$c['name']) ?></option><?php endforeach; ?></select></label><label>Payment<select name="payment"><option value="">All</option><option value="cash" <?= $payment==='cash'?'selected':'' ?>>Cash</option><option value="debit_card" <?= $payment==='debit_card'?'selected':'' ?>>Debit Card</option><option value="credit_card" <?= $payment==='credit_card'?'selected':'' ?>>Credit Card</option></select></label><label>Type<select name="type"><option value="">All</option><option value="income" <?= $type==='income'?'selected':'' ?>>Income</option><option value="expense" <?= $type==='expense'?'selected':'' ?>>Expense</option></select></label><div class="filter-actions"><button class="btn primary">Filter</button><a class="btn secondary" href="<?= e(url('view_transactions.php')) ?>">Reset</a></div></form></section>
<section class="card table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Payment</th><th>Description</th><th>Amount</th><th>Actions</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7" class="center muted">No transactions found.</td></tr><?php endif; ?><?php foreach($rows as $r): ?><tr><td><?= e(date('d M Y',strtotime($r['transaction_date']))) ?></td><td><span class="badge <?= e($r['type']) ?>"><?= e(ucfirst($r['type'])) ?></span></td><td><?= e($r['category_name']) ?></td><td><?= e(ucwords(str_replace('_',' ',$r['payment_method']))) ?></td><td><?= e($r['description']??'') ?></td><td class="<?= $r['type']==='expense'?'expense-text':'income-text' ?>"><?= $r['type']==='expense'?'-':'+' ?><?= money($r['amount']) ?></td><td class="nowrap"><a class="btn tiny" href="<?= e(url('edit_transaction.php?id='.$r['id'])) ?>">Edit</a> <form class="inline" method="post" action="<?= e(url('delete_transaction.php')) ?>" onsubmit="return confirm('Delete this transaction?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($r['id']) ?>"><button class="btn tiny danger">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<?php include __DIR__.'/includes/footer.php'; ?>
