<?php
require_once dirname(__DIR__).'/includes/bootstrap.php';requireSuperAdmin();$pdo=db();$errors=[];$editId=(int)($_GET['edit']??0);$editing=null;
if($editId){$s=$pdo->prepare('SELECT * FROM categories WHERE id=?');$s->execute([$editId]);$editing=$s->fetch();if(!$editing)$editId=0;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);if($action==='delete'){ $s=$pdo->prepare('SELECT COUNT(*) FROM transactions WHERE category_id=?');$s->execute([$id]);if((int)$s->fetchColumn()>0){$pdo->prepare('UPDATE categories SET is_active=0 WHERE id=?')->execute([$id]);flash('success','Category archived because it has transactions.');}else{$pdo->prepare('DELETE FROM categories WHERE id=?')->execute([$id]);flash('success','Category deleted.');}redirect('categories.php');}
$name=trim((string)($_POST['name']??''));$type=$_POST['type']??'';if($name==='')$errors[]='Category name is required.';if(!in_array($type,['income','expense'],true))$errors[]='Invalid category type.';
if(!$errors){try{if($id){$s=$pdo->prepare('UPDATE categories SET name=?,type=?,is_active=1 WHERE id=?');$s->execute([$name,$type,$id]);flash('success','Category updated.');}else{$s=$pdo->prepare('INSERT INTO categories(name,type) VALUES(?,?)');$s->execute([$name,$type]);flash('success','Category added.');}redirect('categories.php');}catch(PDOException $e){$errors[]='A category with that name and type already exists.';}}}
$cats=$pdo->query('SELECT * FROM categories ORDER BY type,name')->fetchAll();$pageTitle='Admin · Categories';include dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><h1>Category Management</h1><p>Super Admin only.</p></div></div><div class="dashboard-grid"><section class="card"><h2><?= $editing?'Edit Category':'Add Category' ?></h2><?php foreach($errors as $e1): ?><div class="alert error"><?= e($e1) ?></div><?php endforeach; ?><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($editing['id']??0) ?>"><label>Name<input name="name" value="<?= e($editing['name']??'') ?>" required></label><label>Type<select name="type"><option value="expense" <?= ($editing['type']??'expense')==='expense'?'selected':'' ?>>Expense</option><option value="income" <?= ($editing['type']??'')==='income'?'selected':'' ?>>Income</option></select></label><button type="submit" class="btn primary full"><?= $editing?'Update Category':'Add Category' ?></button><?php if($editing): ?><a class="btn secondary full" href="<?= e(url('admin/categories.php')) ?>">Cancel</a><?php endif; ?></form></section>
<section class="card table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($cats as $c): ?><tr><td><?= e($c['name']) ?></td><td><?= e(ucfirst($c['type'])) ?></td><td><?= $c['is_active']?'Active':'Archived' ?></td><td><?php if($c['is_active']): ?><a class="btn tiny" href="<?= e(url('admin/categories.php?edit='.$c['id'])) ?>">Edit</a> <form method="post" class="inline" onsubmit="return confirm('Delete/archive this category?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($c['id']) ?>"><button class="btn tiny danger">Delete</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section></div>
<?php include dirname(__DIR__).'/includes/footer.php'; ?>
